apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
type: Opaque
data:
  mysql-user: {{ .Values.secretValue.mysqlUser }}
  mysql-password: {{ .Values.secretValue.mysqlPassword }}
  mysql-root-password: {{ .Values.secretValue.mysqlRootPassword }}
